# Generated by Django 4.1.3 on 2023-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('passw', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='regform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('qualification', models.CharField(max_length=225)),
                ('experiance', models.CharField(max_length=225)),
                ('linkdlnpro', models.CharField(max_length=225)),
                ('jobcat', models.CharField(max_length=225)),
                ('resume', models.CharField(max_length=225)),
            ],
        ),
    ]
